# Haha yes 

# variables 
CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c23
# Wall for all extra warnings
# Wextra for extra warnings or can use -pedantic 
# -std=c23 for C23 standard

all: main.c
	$(CC) $(CFLAGS) main.c -o main

all: main.c 
	$(CC) $(CFLAGS) main.c -o main.exe